### PR TITLE
Homepage design - DB initialization + newsletter route

### PR DESCRIPTION
**Pull request by GregoryNavasarkian**
I got the Homepage looking good. I also Initialized the db and set up a collection for emails submitted via the newsletter link on the homepage. 

image
image

### CODE REVIEW

**Review by Schnaidm — APPROVED** [review]
Looks great!
The email part is not necessary, so I hope it wasn't too annoying for you to add, but it definitely adds nice functionality. 
Right now, you just have it add the email to a database collection, right?

**Comment by GregoryNavasarkian** [comment]
It was pretty simple. I wanted to make sure the dB would connect/save.

**Comment by Schnaidm** [comment]
Great - that was smart to test it:)
The MongoDB file looks great too!

**Comment by GregoryNavasarkian** [comment]
And it just adds the email to a separate collection.

**Pull request merged**
